services:
  - name: mock-payment
    type: web
    plan: free
    branch: main
    runtime: python
    region: singapore
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:router --host 0.0.0.0 --port 8000"
