services:
  - name: mock-payment
    type: web
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:router --host 0.0.0.0 --port 9000"
    plan: free